export const CURSOR_NAMES = [
  "Pixel Pioneer",
  "Cosmic Drifter",
  "Neon Nomad",
  "Velvet Voyager",
  "Lunar Architect",
  "Prism Walker",
  "Ember Scout",
  "Frost Weaver",
  "Solar Sprinter",
  "Drift Maker",
  "Onyx Rider",
  "Silk Phantom",
  "Zinc Wanderer",
  "Amber Seeker",
  "Slate Curator",
  "Nova Dreamer",
  "Rust Artisan",
  "Cloud Hopper",
  "Tide Shaper",
  "Dusk Traveler",
] as const;

export const CURSOR_COLORS = [
  "#E57373",
  "#F06292",
  "#BA68C8",
  "#7986CB",
  "#64B5F6",
  "#4DD0E1",
  "#4DB6AC",
  "#81C784",
  "#FFD54F",
  "#FF8A65",
] as const;
